SELECT
  e.NOMBRE,
  e.APELLIDO,
  COUNT(e.ID) AS NUMERO_DE_SOLICITUDES_VACACIONES
FROM EMPLEADO e
JOIN VACACIONES v ON v.ID_EMP = e.ID
GROUP BY e.ID, e.NOMBRE, e.APELLIDO
HAVING COUNT(e.ID) > ?
ORDER BY NUMERO_DE_SOLICITUDES_VACACIONES DESC;