SELECT
  e.NOMBRE,
  e.APELLIDO,
  COALESCE(SUM(CASE WHEN v.ESTADO = 'A' THEN v.CANTIDAD_DIAS ELSE 0 END), 0) AS DIAS_APROBADOS,
  COALESCE(SUM(CASE WHEN v.ESTADO = 'R' THEN v.CANTIDAD_DIAS ELSE 0 END), 0) AS DIAS_RECHAZADOS
FROM EMPLEADO e
LEFT JOIN VACACIONES v ON v.ID_EMP = e.ID
GROUP BY e.ID